DROP TABLE IF EXISTS plates;
DROP TABLE IF EXISTS access_attempts;
DROP TABLE IF EXISTS tokens;

CREATE TABLE plates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plate TEXT UNIQUE NOT NULL
);

CREATE TABLE access_attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    img_path TEXT UNIQUE NOT NULL,
    plate TEXT NOT NULL DEFAULT '',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plate_id INTEGER NOT NULL,
    token TEXT NOT NULL,
    FOREIGN KEY (plate_id) REFERENCES plates (id)
);
